# Configuration SOPS pour nixos-kid
#
# Utilise la clé SSH de l'hôte (plus simple que age)
#
# IMPORTANT: Remplacer YOUR_SSH_HOST_KEY par votre clé publique SSH convertie en age
#
# Pour obtenir la clé:
#   1. Convertir la clé SSH en format age:
#      nix-shell -p ssh-to-age --run 'ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub'
#      OU
#      ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
#
#   2. Copier la sortie (age1xxxx...) et remplacer ci-dessous

keys:
  - &host YOUR_SSH_HOST_KEY

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *host
