# Example flake.nix for /etc/nixos/flake.nix
# Shows how to use the nixos-kid flake with SOPS secrets
#
# IMPORTANT: v2.0+ requires SOPS - see README.md for setup instructions

{
  description = "Kid-friendly NixOS laptop configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Import nixos-kid flake
    # Option 1: From GitHub (recommended for reproducibility)
    nixos-kid.url = "github:likarum/nixos-kid";

    # Option 2: From local path (for development)
    # nixos-kid.url = "path:/etc/nixos/nixos-kid";

    # Option 3: Pin to specific version
    # nixos-kid.url = "github:likarum/nixos-kid/v2.0.0";
  };

  outputs = { self, nixpkgs, nixos-kid }: {
    nixosConfigurations = {
      # Your machine name (adapt to your hostname)
      laptop-enfant = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          # Hardware configuration (generated by nixos-generate-config)
          ./hardware-configuration.nix

          # Import all nixos-kid modules (includes SOPS support)
          nixos-kid.nixosModules.default

          # Your custom configuration
          ({ config, pkgs, ... }: {
            # System basics
            networking.hostName = "laptop-enfant";
            time.timeZone = "Europe/Paris";
            system.stateVersion = "24.11";

            # REQUIRED: Configure SOPS secrets path
            kidFriendly.sops.secretsFile = ./nixos-kid/secrets.yaml;

            # Enable all kid-friendly protections
            kidFriendly = {
              adguardHome.enable = true;
              dnsEnforcement.enable = true;

              browserPolicies = {
                enable = true;
                firefox.enable = true;
                chromium.enable = true;
              };

              firewall = {
                enable = true;
                blockDoHProviders = true;
                blockProxiesAndVPN = true;  # New in v2.0
              };

              servicesBlocklist = {
                enable = true;
                # Customize which services to block
                # blockSteam = true;  # Uncomment to block Steam
              };
            };

            # User configuration
            users.users.admin = {
              isNormalUser = true;
              extraGroups = [ "wheel" "networkmanager" ];
              # Set your password or use passwordFile
            };

            # Desktop environment (example)
            services.xserver = {
              enable = true;
              displayManager.gdm.enable = true;
              desktopManager.gnome.enable = true;
            };

            # Other system configuration...
          })
        ];
      };
    };
  };
}
